### ISSUE TITLE
Refactor checkmodel, makemodel, checkdata, osdatapackage

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-datastore-cli#22]
# Description

The POC of this tool was written before anything else for OpenSpending Next existed... including a working title :). `checkmodel`, `makemodel`, `checkdata` and `osdatapackage` all need significant changes in order to work with the current state of play.

# Tasks

*Requires: https://github.com/openspending/os-authz-service/issues/1*

* [x] Encourage use of `good tables` and `jsontableschema` to check data and infer schemas as part of making a fiscal data package before running the CLI directly (probably a documentation task that @pwalsh will do)
* [x] The whole `osdatapackage` package can be removed
* [x] `makemodel`: an interactive data modeler could be fun in a CLI, but, let's consider it an enhancement for now, and focus on the other aspects of the CLI, so, **remove it**, to be picked up later [here](https://github.com/openspending/os-datastore-cli/issues/23))
* [x] `checkmodel` > `validate package`: `check model` basically is just [`datapackage-validate`](https://github.com/okfn/datapackage-validate-py) against a [Fiscal Data Package schema](https://github.com/dataprotocols/schemas/blob/master/fiscal-data-package.json) (which is of course pulled in from the registry by [`datapackage-registry`](https://github.com/okfn/datapackage-registry-py)). Adapt the code to use these libs and adapt the CLI interface accordingly.
* [x] `checkdata` > `validate data`: `checkdata` is basically a `goodtables` batch pipeline processor over all the resources in the data package. This should simply continue to work as is. Perhaps we should simplify some of the attempt at an interactive experience here, as it is overly complex and not really helpful. Let's address this when the work is being done.

**Comment by pwalsh** [comment]
DONE.
